# Generated by Django 5.0.2 on 2024-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_job_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
